replicaCount: 1

mysql:
  databaseName: mysql
  fullname: mysql

springApp:
  image:
    repository: localhost:8082/toystore
    pullPolicy: IfNotPresent
    tag: latest

mysqlVolume:
  persistentVolumeClaim:
    storageSize: 500Mi  #1Gi

  persistentVolume:
    storageSize: 500Mi  #1Gi
    pathOnHost: /var/lib/mysql


  mountPath: /var/lib/mysql
