{{- with .Values.nexus }}
apiVersion: v1
kind: Secret
metadata:
  name: nexus-registry-secret
data:
  .dockerconfigjson: {{ .dockerconfigjson | b64enc | quote }}
type: kubernetes.io/dockerconfigjson
{{- end }}